format = """
[](COLOR1)\
$os\
$username\
[](bg:COLOR2 fg:COLOR1)\
$directory\
[](fg:COLOR2 bg:COLOR3)\
$git_branch\
$git_status\
[](fg:COLOR3 bg:COLOR4)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:COLOR4 bg:COLOR5)\
$docker_context\
[](fg:COLOR5 bg:COLOR6)\
$time\
[ ](fg:COLOR6)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:COLOR1"
style_root = "bg:COLOR1"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:COLOR1"
disabled = true # Disabled by default

[directory]
style = "bg:COLOR2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:COLOR5"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:COLOR3"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:COLOR3"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:COLOR4"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:COLOR6"
format = '[ 󰋄 $time ]($style)'
